---
- hosts: nodes 

  tasks:
  - name: Install Docker
    yum: pkg=docker state=present 
  - name: stop docker service 
    service: name=docker state=stopped 
  - name: remove default docker files
    shell: rm -rf /var/lib/docker/*
  - name: start docker service 
    service: name=docker state=started
  - name: docker storage setup 
    shell: docker-storage-setup
