---
- hosts: nodes 

- name: Install Docker
  apt_rpm:  
    pkg: docker
    state: present
  tags: 
  - nodes
  - docker-setup  

- name: stop docker service 
  service: name=docker state=stopped 
  tags: 
  - docker-setup  
  
- name: remove default docker files
  shell: rm -rf /var/lib/docker/*
  tags: 
  - docker-setup  
          
- name: start docker service 
  service: name=docker state=started
  tags: 
  - docker-setup  

- name: docker storage setup 
  shell: docker-storage-setup
  tags: 
  - docker-setup  

