---
# TODO: Enhance redhat_subscription module
#       to make it able to attach to a pool
#       to make it able to enable repositories

- set_fact:
    rhel_subscription_user: "{{ lookup('oo_option', 'rhel_subscription_user') | default(rhsub_user, True) | default(omit, True) }}"
    rhel_subscription_pass: "{{ lookup('oo_option', 'rhel_subscription_pass') | default(rhsub_pass, True) | default(omit, True) }}"
    rhel_subscription_server: "{{ lookup('oo_option', 'rhel_subscription_server') | default(rhsub_server) }}"
    rhel_subscription_pool: "{{ lookup('oo_option', 'rhel_subscription_pool') | default(rhsub_pool, True) | default(omit, True) }}"

- fail:
    msg: "This role is only supported for Red Hat hosts"
  when: ansible_distribution != 'RedHat'

- fail:
    msg: Either rsub_user or the rhel_subscription_user env variable are required for this role.
  when: rhel_subscription_user is not defined

- fail:
    msg: Either rsub_pass or the rhel_subscription_pass env variable are required for this role.
  when: rhel_subscription_pass is not defined

- name: RedHat subscriptions
  redhat_subscription:
    username: "{{ rhel_subscription_user }}"
    password: "{{ rhel_subscription_pass }}"
    autosubscribe: no

- include: enterprise.yml
  when: deployment_type in [ 'enterprise', 'atomic-enterprise', 'openshift-enterprise' ]

- include: origin-rhel.yml
  when: deployment_type == 'origin'

- name: Retrieve the OpenShift Pool ID
  command: subscription-manager list --available --matches="{{ rhel_subscription_pool }}" --pool-only
  register: openshift_pool_id
  changed_when: False

- name: Attach to OpenShift Pool
  command: subscription-manager subscribe --pool {{ openshift_pool_id.stdout_lines[0] }}
  autosubscribe: no

- include: enterprise.yml
  when: deployment_type in [ 'enterprise', 'atomic-enterprise', 'openshift-enterprise' ] and
        not openshift.common.is_atomic | bool

- include: origin-rhel.yml
  when: deployment_type == 'origin'
